#!/bin/bash

#---------------- Folder Arrangement ------------#
#                  |- train                      #
#         |- Data -|- test                       #
# ~/home -|- Packages                            #
#         |- Output -|- train                    #
#                    |- test                     #
#------------------------------------------------#

root_path='/home/elec5622'
data_root=$root_path'/Data/'
package_DIR=$root_path'/Packages/'

output_path=$root_path'/Output/'
train_output_path=$root_path'/Output/train/'
test_output_path=$root_path'/Output/test/'
floImg=$package_DIR'MNI152_T1_1mm_brain.nii'
aalImg=$package_DIR'aal.nii'

#====================  measurement =======================#
echo "=============== begin measurement... ========"

#----- processing training images
cd $data_root'train/'
subIDs=`ls`

for subID in $subIDs 
do
    echo "Processing training image "$subID
    fileext='.nii.gz'
    file=$subID
    basename $file $fileext
    filename="${file%%.*}"

    subGMMask=$train_output_path$filename'_greymatter_mask.nii.gz'
    aalmask="aal_to_"$filename"_stripped_transformed.nii.gz" # Corrected filename

    echo " >>>> Create measurements for "$filename"  <<<<<<"
    source ${root_path}/CreateSeedMask $train_output_path 'aal_to_'$filename"_stripped_transformed"$fileext 
    echo "i am done!"
    seedMask_path=$train_output_path'seedMasks/'
    cd $seedMask_path
    mask_IMGs=`ls | wc -l`	
        
    echo -n $filename >> ${train_output_path}"AAL_statistics_volumn_train.csv"

    for mask in *.nii.gz; do
        # Calculate the volume using fslstats
        
        volume=$(fslstats $mask -V | cut -d ' ' -f2)
        
        # Append the volume to the CSV file
        echo -n ", $volume" >> ${train_output_path}"AAL_statistics_volumn_train.csv"
    done

    echo "" >> ${train_output_path}"AAL_statistics_volumn_train.csv" # End the row for the current image

    rm '-rf' $seedMask_path   
    cd $data_root'train/'
done

#----- processing test images
cd $data_root'test/'
subIDs=`ls`

for subID in $subIDs 
do
    echo "Processing test image "$subID
    fileext='.nii.gz'
    file=$subID
    basename $file $fileext
    filename="${file%%.*}"

    subGMMask=$test_output_path$filename'_greymatter_mask.nii.gz'
    aalmask="aal_to_"$filename"_stripped_transformed.nii.gz" # Corrected filename

    echo " >>>> Create measurements for "$filename"  <<<<<<"
    source ${root_path}/CreateSeedMask $test_output_path 'aal_to_'$filename"_stripped_transformed"$fileext 

    seedMask_path=$test_output_path'seedMasks/'
    cd $seedMask_path
    mask_IMGs=`ls | wc -l`	
        
    echo -n $filename >> ${test_output_path}"AAL_statistics_volumn_test.csv"

    for mask in *.nii.gz; do
        # Calculate the volume using fslstats
        volume=$(fslstats $mask -V | cut -d ' ' -f2)
        
        # Append the volume to the CSV file
        echo -n ", $volume" >> ${test_output_path}"AAL_statistics_volumn_test.csv"
    done

    echo "" >> ${test_output_path}"AAL_statistics_volumn_test.csv" # End the row for the current image

    rm '-rf' $seedMask_path   
    cd $data_root'test/'
done

#==================== End of measurement  =========#

